apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: h5c0v41zt-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/h5c0v41zt-java-quarkus-gitops